/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTestsRouteImport } from './routes/_authenticated/tests'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAeoRouteImport } from './routes/_authenticated/aeo'
import { Route as AuthenticatedTestsTestIdRouteImport } from './routes/_authenticated/tests.$testId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestsRoute = AuthenticatedTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAeoRoute = AuthenticatedAeoRouteImport.update({
  id: '/aeo',
  path: '/aeo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTestsTestIdRoute =
  AuthenticatedTestsTestIdRouteImport.update({
    id: '/$testId',
    path: '/$testId',
    getParentRoute: () => AuthenticatedTestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aeo': typeof AuthenticatedAeoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tests': typeof AuthenticatedTestsRouteWithChildren
  '/tests/$testId': typeof AuthenticatedTestsTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aeo': typeof AuthenticatedAeoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tests': typeof AuthenticatedTestsRouteWithChildren
  '/tests/$testId': typeof AuthenticatedTestsTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/aeo': typeof AuthenticatedAeoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tests': typeof AuthenticatedTestsRouteWithChildren
  '/_authenticated/tests/$testId': typeof AuthenticatedTestsTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/aeo'
    | '/dashboard'
    | '/settings'
    | '/tests'
    | '/tests/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/aeo'
    | '/dashboard'
    | '/settings'
    | '/tests'
    | '/tests/$testId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/aeo'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/tests'
    | '/_authenticated/tests/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tests': {
      id: '/_authenticated/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AuthenticatedTestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aeo': {
      id: '/_authenticated/aeo'
      path: '/aeo'
      fullPath: '/aeo'
      preLoaderRoute: typeof AuthenticatedAeoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tests/$testId': {
      id: '/_authenticated/tests/$testId'
      path: '/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof AuthenticatedTestsTestIdRouteImport
      parentRoute: typeof AuthenticatedTestsRoute
    }
  }
}

interface AuthenticatedTestsRouteChildren {
  AuthenticatedTestsTestIdRoute: typeof AuthenticatedTestsTestIdRoute
}

const AuthenticatedTestsRouteChildren: AuthenticatedTestsRouteChildren = {
  AuthenticatedTestsTestIdRoute: AuthenticatedTestsTestIdRoute,
}

const AuthenticatedTestsRouteWithChildren =
  AuthenticatedTestsRoute._addFileChildren(AuthenticatedTestsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAeoRoute: typeof AuthenticatedAeoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTestsRoute: typeof AuthenticatedTestsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAeoRoute: AuthenticatedAeoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTestsRoute: AuthenticatedTestsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
